### ISSUE TITLE
Add support for Bitbucket to Keybase

### ISSUE THREAD

**Issue by mark-adams** [keybase/proofs#19]
Atlassian Bitbucket [launched](https://blog.bitbucket.org/2015/03/18/snippets-for-teams-are-here-with-a-rich-set-of-apis/) their Snippets feature today which allows developers to post arbitrary pieces of code publicly. With the addition of this feature, users should now be able to create Bitbucket proofs.

Documentation for the API is available here: https://confluence.atlassian.com/display/BITBUCKET/snippets+Endpoint

**Comment by virtualdxs** [comment]
When does this come into the release client?

**Comment by kg4zow** [comment]
I hate to sound like "me too", but ... any idea when this will make it into the release clients?

**Comment by computator** [comment]
Just wondering what happened to this since it was merged nearly 4 years ago.
@maxtaco

**Comment by maxtaco** [comment]
we now have a new system to do this!

https://keybase.io/docs/proof_integration_guide

**Comment by computator** [comment]
I did see that, however that requires us to wait on bitbucket to add support. If we already have code written for bitbucket that uses snippets, just like GitHub has explicit code for gists, then why not use it?

**Comment by maxtaco** [comment]
There's a lot of tooling around doing it the old way that never got done because there wasn't enough interest internally and externally.  The new way has us automating the tooling but does require the other side to help out. But it lends to a smoother experience. We're happy to help them out if they'd be interested in this.
