### ISSUE TITLE
http / https proof not functioning

### ISSUE THREAD

**Issue by fhorlaville** [keybase/proofs#64]
Hi, I have recently switched web servers and had forgotten to move the keybase.txt file along, so rightfully I got the message that the web proof couldn't be verified. I have put the file back in place and checked it's working but can't re-enable the proof.
The keybase.io web server says it's not there (although it is) and the keybase app says it can't generate a new one because it's already present.
Any suggestion?

- https://keybase.io/fhorlaville
- https://www.tamsoftware.info/keybase.txt

Thanks

**Comment by oconnor663** [comment]
`keybase id fhorlaville` is failing too. In my logs (`keybase -d id -s fhorlaville`) I only see
```
2017-05-03T18:56:13.853660-04:00 ▶ [DEBU keybase log.go:30] 10d - API GET https://www.tamsoftware.info/.well-known/keybase.txt: err=ERROR: 404 Not Found, status="404 Not Found", jsonBytes=0 [tags:ID2=i8-KmHlNgeHC,API=Y2kdgRTAIcDh]
✔ Proof for www.tamsoftware.info failed: 404 Not Found (code=240)
```

@mlsteele, do you know if there's a PVL-related reason we wouldn't also be hitting https://www.tamsoftware.info/keybase.txt?

**Comment by mlsteele** [comment]
@oconnor663 The client gets a hint of where to look from the server and only looks there. The server tries both locations but only until it finds a success. I guess when it starts failing the server only rechecks from its hint.

@fhorlaville The simplest thing to do until we make this better is to just revoke/redo the domain proof.

This is the same issue as https://github.com/keybase/keybase-issues/issues/2966

**Comment by fhorlaville** [comment]
Thanks a lot, @oconnor663 and @mlsteele , for your quick answers.
I will do as suggested. I will also take a look at the code doing this proof to see if I can offer a solution.
Would it be too much to ask which repo I should clone and look into?

Thanks,

Franck Horlaville
TAM Software

**Comment by oconnor663** [comment]
All the code you're running locally is in https://github.com/keybase/client. What went wrong in this case is server code though, which is not open source. In general the server tells clients where to look for a proof, and the clients do all the verification locally, but it was the where-to-look that was broken. (We might be able to get rid of this mechanism for web proofs in particular, since there are only a couple possible locations, but it's necessary for services like Facebook and Twitter, where we can't have clients crawling your entire post history every time they try to ID you.)

**Comment by fhorlaville** [comment]
Now it gets even weirder ; I’ve created it as well in the other location, checked it, see that it’s being requested but it’s still broken

54.84.133.185 - - [11/May/2017:21:09:59 +0100] "GET /.well-known/keybase.txt HTTP/1.1" 200 2566 "-" "keybase-proofs/2.1.11"

**Comment by oconnor663** [comment]
@fhorlaville I'm seeing `Signature not found in body` when I ID you. Is that consistent with what you're seeing?

The error is probably that the file at https://www.tamsoftware.info/.well-known/keybase.txt is an old proof, rather than the one that was generated when you proved the domain most recently. When I look at [your sigchain](https://keybase.io/fhorlaville/chain), I see that your most recent proof for tamsoftware.info is at `"seqno": 6`, but the file you're hosting is `"seqno": 2`.

**Comment by fhorlaville** [comment]
I deleted it all and re-created it ; all is fine now but wasn’t easy as the keybase app kept saying there was already a live proof.

Sorry for the hassle!

Franck

**Comment by jayvdb** [comment]
Is there a problem which can be fixed in this repo?
Or should this be closed?
