### ISSUE TITLE
Proof request: Mastodon

### ISSUE THREAD

**Issue by selfagency** [keybase/proofs#72]
Please add support for verifying one's self on [tootsuite/mastodon](/tootsuite/mastodon) instances.

**Comment by howardjp** [comment]
I would like to support this and note that because of the distributed nature of the Mastodon network, Keybase verification would be very helpful.  This mitigates that new accounts with the same name but hosted on a different node are confused with the "real" account.  In addition, while imperfect on Twitter, Mastodon cannot replicate the blue-check mechanism.  So Keybase would be the only reasonable verification system.

It helps that it should be relatively simple to modify the existing Twitter verification code.  I think :)

**Comment by xkr47** [comment]
Yeah.. a "keybase verified" icon would be nice.. :)

It seems the main discussion is happening in the issue keybase/keybase-issues#2948, where the main developer (Gargron) has apparently gotten involved in discussions with keybase staff.

**Comment by hexandcube** [comment]
I think that this can be closed.

[keybase.io/blog/keybase-proofs-for-mastodon-and-everyone](https://keybase.io/blog/keybase-proofs-for-mastodon-and-everyone)

**Comment by Fordi** [comment]
Not to whine, but I'm on a public mastodon instance that isn't in the keybase proofs list, `retro.pizza`.  Is there an avenue to get it added?  I want to ping my admin about it.

**Comment by hexandcube** [comment]
Keybase integration has been removed from Mastodon since Keybase got acquired by Zoom and abandoned the project. 

https://github.com/mastodon/mastodon/pull/17045
